import React from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';

// --- (Components and Animation Variants are unchanged) ---
const fadeIn = { hidden: { opacity: 0, y: 20 }, visible: { opacity: 1, y: 0, transition: { duration: 0.6, ease: 'easeInOut' } }};
const staggerContainer = { hidden: { opacity: 0 }, visible: { opacity: 1, transition: { staggerChildren: 0.1 } }};
const BenefitDetailCard = ({ icon, title, description }) => ( <motion.div variants={fadeIn} whileHover={{ y: -8, scale: 1.03 }} className="bg-white p-6 rounded-lg shadow-md flex items-start cursor-pointer transition-shadow duration-300 hover:shadow-xl h-full"><div className="flex-shrink-0 text-accent mr-4 mt-1">{icon}</div><div><h3 className="font-unbounded text-md font-bold text-primary">{title}</h3><p className="text-slate-600 mt-1 text-sm">{description}</p></div></motion.div> );
const StepCard = ({ icon, title, description }) => ( <motion.div variants={fadeIn} className="p-4 text-center"><div className="inline-block bg-accent/10 text-accent p-4 rounded-full mb-4">{icon}</div><h3 className="font-unbounded text-lg font-bold text-primary mb-2">{title}</h3><p className="text-slate-600">{description}</p></motion.div> );


const DataEntry = () => {
  const keyBenefits = [
    { title: "Significant Cost Savings", description: "Hire Indian data analysts experts for up to 70–80% lower cost than local staffing, with flexible packages.", icon: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}><path strokeLinecap="round" strokeLinejoin="round" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v.01" /></svg> },
    { title: "Highly Skilled Workforce", description: "Access a large pool of trained operators familiar with medical, legal, ecommerce, and real estate requirements.", icon: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}><path strokeLinecap="round" strokeLinejoin="round" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0" /></svg> },
    { title: "Round-the-Clock Productivity", description: "The time zone difference lets you send tasks at your EOD and receive completed work by morning.", icon: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}><path strokeLinecap="round" strokeLinejoin="round" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" /></svg> },
    { title: "Scalable & Flexible Solutions", description: "Easily scale your data analysts team up or down to match project requirements without the hassle of permanent hires.", icon: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}><path strokeLinecap="round" strokeLinejoin="round" d="M4 8V4m0 0h4M4 4l5 5m11-1V4m0 0h-4m4 0l-5 5M4 16v4m0 0h4m-4 0l5-5m11 1v4m0 0h-4m4 0l-5-5" /></svg> },
    { title: "Advanced Technology Adoption", description: "We use the latest automation, RPA, and management software to ensure efficient, error-free data analysts.", icon: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}><path strokeLinecap="round" strokeLinejoin="round" d="M5 12h14M5 12a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v4a2 2 0 01-2 2M5 12a2 2 0 00-2 2v4a2 2 0 002 2h14a2 2 0 002-2v-4a2 2 0 00-2-2m-2-4h.01M17 16h.01" /></svg> },
    { title: "Data Security & Confidentiality", description: "Robust security measures and encrypted data transfer to protect your sensitive business information.", icon: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}><path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" /></svg> },
  ];

  return (
    <div className="bg-white">
      {/* (Sections 1-4 are unchanged) */}
      <section className="relative text-white py-20 md:py-32"> <div className="absolute inset-0 bg-primary opacity-80 z-10"></div> <img src="https://plus.unsplash.com/premium_photo-1679922389798-8b38c78b5670?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="Person efficiently typing on a keyboard" className="absolute inset-0 w-full h-full object-cover"/> <motion.div initial="hidden" animate="visible" variants={staggerContainer} className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-20 text-center"> <motion.h1 variants={fadeIn} className="font-unbounded text-4xl md:text-6xl font-extrabold">Dedicated Data Analysts Experts</motion.h1> <motion.p variants={fadeIn} className="mt-4 text-lg md:text-xl text-slate-300 max-w-3xl mx-auto"> Boost productivity and cut costs by outsourcing your data analysts to our dedicated virtual experts from India. </motion.p> </motion.div> </section>
      <section className="py-20 md:py-28 bg-slate-50"> <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"> <div className="text-center mb-16"> <h2 className="font-unbounded text-3xl md:text-4xl font-bold text-primary">Our Simple Process</h2> </div> <div className="grid grid-cols-1 md:grid-cols-3 gap-8"> <StepCard icon={<svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}><path strokeLinecap="round" strokeLinejoin="round" d="M9 13h6m-3-3v6m5 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>} title="1. Send Requirements" description="Discuss your project details and select your preferred expert or team." /> <StepCard icon={<svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}><path strokeLinecap="round" strokeLinejoin="round" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" /></svg>} title="2. Execution" description="Your tasks are performed with regular progress updates and agreed-upon milestones." /> <StepCard icon={<svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}><path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>} title="3. Delivery & Support" description="Receive accurate, timely results, plus ongoing support and scalability for future needs." /> </div> </div> </section>
      <section className="py-20 md:py-28 bg-white"> <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"> <div className="text-center mb-16"> <h2 className="font-unbounded text-3xl md:text-4xl font-bold text-primary">Key Benefits of Outsourcing data analysts</h2> </div> <motion.div variants={staggerContainer} initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.1 }} className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6"> {keyBenefits.map((service) => ( <BenefitDetailCard key={service.title} icon={service.icon} title={service.title} description={service.description} /> ))} </motion.div> </div> </section>
      <section className="py-20 md:py-28 bg-slate-50"> <motion.div initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.3 }} variants={staggerContainer} className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid md:grid-cols-2 gap-12 items-center"> <motion.div variants={fadeIn} className="pr-0 md:pr-12"> <h2 className="font-unbounded text-3xl font-bold text-primary mb-4">A Global Extension of Your Team</h2> <p className="text-slate-600 mb-6 leading-relaxed"> Our virtual data analysts experts are more than just contractors; they are a seamless extension of your in-house operations. With a focus on professionalism and clear communication, we provide: </p> <ul className="space-y-3"> <li className="flex items-center"><span className="text-accent mr-3">&#10003;</span> English-speaking teams for easy collaboration.</li> <li className="flex items-center"><span className="text-accent mr-3">&#10003;</span> Diverse industry coverage (legal, ecommerce, etc.).</li> <li className="flex items-center"><span className="text-accent mr-3">&#10003;</span> The time-zone advantage for 24/7 productivity.</li> </ul> </motion.div> <motion.div variants={fadeIn} className="rounded-xl overflow-hidden shadow-2xl"> <img src="https://plus.unsplash.com/premium_photo-1679922389798-8b38c78b5670?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="Global team collaborating online" className="w-full h-full object-cover" /> </motion.div> </motion.div> </section>

      {/* --- SECTION 5: CORRECTED Final CTA --- */}
      <section className="relative text-white py-20">
         <div className="absolute inset-0 bg-primary opacity-90 z-10"></div>
         <img src="https://images.unsplash.com/photo-1521791136064-7986c2920216?q=80&w=2070&auto=format&fit=crop" alt="Team discussing work" className="absolute inset-0 w-full h-full object-cover"/>
         <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center relative z-20">
            <motion.h2 initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.5 }} variants={fadeIn} className="font-unbounded text-3xl md:text-4xl font-bold">
                Optimize Your Business Operations
            </motion.h2>
            <motion.div initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.5 }} variants={fadeIn}>
                 <Link to="/contact" className="bg-accent text-primary font-bold py-3 px-8 rounded-lg text-lg hover:bg-yellow-500 transition duration-300 transform hover:scale-105 inline-block mt-8">
                    Hire a data analysts Expert
                </Link>
            </motion.div>
        </div>
      </section>
    </div>
  );
};

export default DataEntry;